@startuml
!pragma layout smetana
!theme reddress-darkorange

entity user {
    id
    username
    firstName
    lastName
    phone
    email
    password
    role
    diyComments
    workshops
    badges
}

entity workshop {
    id
    title
    picture
    street_number
    street
    postcode
    city
    reservationUser
    date
    description
    comments
    longitude
    latitude
    diyUser
    numberOfPeople
    confirmation
}

entity comment {
    id
    comment
    created_at
    diyWorkshop
    diyUser
    boolean confirmation
}


entity Badge {
    id
    name
    picturePath
}

entity footer {
    id
    name
    socialNetworkPath
    picturePath
    visible
}

entity role {
    id
    name

}

entity WorkshopReservationUser {
userID
workshopID

}






user "m" -- "1" workshop
user "m" -- "1" Badge
comment "m" -- "1" workshop
comment "m" -- "1" user
workshop "m" -- "m" WorkshopReservationUser
WorkshopReservationUser "1" -- "1" user
workshop "m" -- "1" user

@enduml