@startuml
!pragma layout smetana
!theme reddress-darkorange

entity user {
    id
    username
    password
    first_name
    last_name
    mail
    address | null
    phone | null
    role
}

entity atelier {
    id
    title
    picture
    street_number
    street
    postcode
    city
    description

    comment
    inscription
    numberOfPeople
}

entity comment {
    id
}

atelier "1.1" -- "1.n" comment

@enduml