@startuml
!pragma layout smetana
!theme reddress-darkorange

entity user {
    id
    username
    password
    mail
    role
}

entity profile {
    first_name
    last_name
    address
    phone
}

entity workshop {
    id
    title
    picture
    street_number
    street
    postcode
    city
    description
    numberOfPeople
    boolean confirmation
}

entity comment {
    id
    comment
    created_at
    boolean confirmation
}

entity inscription {
    id
    workshop_id
    user_id
}

user "1.1" -- "1.1" profile
comment "m" -- "1" workshop
comment "m" -- "1" user
inscription "m" -- "m" user
inscription "m" -- "m" workshop
workshop "m" -- "1" user

@enduml